FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /code/

RUN python manage.py collectstatic --no-input

RUN pip install gunicorn

RUN apt-get update && apt-get install -y nginx

COPY nginx.conf /etc/nginx/sites-available/default

EXPOSE 80

CMD service nginx start && gunicorn FinanceBackend.wsgi:application --bind 0.0.0.0:8000
