version: '3.10'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '8000:8000'
    command: >
      sh -c 'python3 ./manage.py migrate &&
      python3 ./manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
