# Generated by Django 4.1.3 on 2022-11-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('IC', 'Постоянные'), ('VC', 'Переменные')], default='IC', max_length=2),
        ),
    ]
