# Generated by Django 4.1.2 on 2022-10-14 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractcash',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='abstractcash',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='abstractcash',
            name='reg_sum',
            field=models.IntegerField(verbose_name='Постоянная сумма'),
        ),
        migrations.AlterField(
            model_name='abstractcash',
            name='var_sum',
            field=models.IntegerField(verbose_name='Переменная сумма'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryName',
            field=models.CharField(default='Название категории', max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='incomecash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
