# Generated by Django 4.1.3 on 2022-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='income_outcome',
            field=models.CharField(choices=[('income', 'Категория доходов'), ('outcome', 'Категория расходов')], default='income', max_length=11),
        ),
    ]
