# Generated by Django 4.1.3 on 2023-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
