# Generated by Django 4.1.2 on 2022-10-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_abstractcash_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxName', models.CharField(max_length=255, verbose_name='Название копилки')),
                ('boxSumm', models.IntegerField(verbose_name='Сумма в копилке')),
            ],
        ),
    ]
