# Generated by Django 4.1.3 on 2022-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categories_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('CC', 'Постоянные'), ('OC', 'Разовые')], default='CC', max_length=2),
        ),
    ]
