# Generated by Django 4.1.3 on 2022-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_categories_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('constant', 'Постоянные'), ('once', 'Разовые')], default='constant', max_length=8),
        ),
    ]
