# Generated by Django 4.2.11 on 2024-04-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_populate_outcome_categories_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='Пользователь FinanceApp', null=True),
        ),
    ]
