# Generated by Django 4.2.11 on 2024-04-04 09:21

import api.models.users
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.users.CustomUserManager()),
            ],
        ),
    ]
