# Generated by Django 4.1.3 on 2022-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_categories_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecash',
            name='var_sum',
            field=models.IntegerField(verbose_name='Разовая сумма'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='var_sum',
            field=models.IntegerField(verbose_name='Разовая сумма'),
        ),
    ]
