# Generated by Django 4.1.3 on 2022-12-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_incomecash_date_record_outcomecash_date_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecash',
            name='date_record',
            field=models.DateTimeField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='date_record',
            field=models.DateTimeField(verbose_name='Дата записи'),
        ),
    ]
