# Generated by Django 4.1.3 on 2022-11-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_incomecash_var_sum_alter_outcomecash_var_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomecash',
            old_name='reg_sum',
            new_name='constant_sum',
        ),
        migrations.RenameField(
            model_name='incomecash',
            old_name='var_sum',
            new_name='once_sum',
        ),
        migrations.RenameField(
            model_name='outcomecash',
            old_name='reg_sum',
            new_name='constant_sum',
        ),
        migrations.RenameField(
            model_name='outcomecash',
            old_name='var_sum',
            new_name='once_sum',
        ),
    ]
