# Generated by Django 4.2.11 on 2024-04-26 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomes",
            name="type",
        ),
        migrations.RemoveField(
            model_name="outcomes",
            name="type",
        ),
    ]
