# Generated by Django 4.1.3 on 2022-12-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_incomecash_date_alter_incomecash_date_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecash',
            name='date',
            field=models.DateField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='date',
            field=models.DateField(verbose_name='Дата записи'),
        ),
    ]
