# Generated by Django 4.1.3 on 2022-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_reg_sum_incomecash_constant_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecash',
            name='constant_sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Постоянная сумма'),
        ),
        migrations.AlterField(
            model_name='incomecash',
            name='once_sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Разовая сумма'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='constant_sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Постоянная сумма'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='once_sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Разовая сумма'),
        ),
    ]
