# Generated by Django 4.2.11 on 2024-04-26 18:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_incomes_type_remove_outcomes_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accumulations",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966884)
            ),
        ),
        migrations.AlterField(
            model_name="accumulations",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966935)
            ),
        ),
        migrations.AlterField(
            model_name="incomecategories",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966884)
            ),
        ),
        migrations.AlterField(
            model_name="incomecategories",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966935)
            ),
        ),
        migrations.AlterField(
            model_name="incomes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966884)
            ),
        ),
        migrations.AlterField(
            model_name="incomes",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966935)
            ),
        ),
        migrations.AlterField(
            model_name="outcomecategories",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966884)
            ),
        ),
        migrations.AlterField(
            model_name="outcomecategories",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966935)
            ),
        ),
        migrations.AlterField(
            model_name="outcomes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966884)
            ),
        ),
        migrations.AlterField(
            model_name="outcomes",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966935)
            ),
        ),
        migrations.AlterField(
            model_name="targets",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966884)
            ),
        ),
        migrations.AlterField(
            model_name="targets",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966935)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966884)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 26, 21, 56, 58, 966935)
            ),
        ),
    ]
