# Generated by Django 4.1.3 on 2023-05-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_moneybox_box_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneybox',
            name='box_type',
        ),
    ]
