# Generated by Django 4.2.11 on 2024-04-29 07:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_accumulations_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accumulations",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 29, 10, 34, 12, 66380)
            ),
        ),
        migrations.AlterField(
            model_name="accumulations",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="incomecategories",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 29, 10, 34, 12, 66380)
            ),
        ),
        migrations.AlterField(
            model_name="incomecategories",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="incomes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 29, 10, 34, 12, 66380)
            ),
        ),
        migrations.AlterField(
            model_name="incomes",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="outcomecategories",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 29, 10, 34, 12, 66380)
            ),
        ),
        migrations.AlterField(
            model_name="outcomecategories",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="outcomes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 29, 10, 34, 12, 66380)
            ),
        ),
        migrations.AlterField(
            model_name="outcomes",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="targets",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 29, 10, 34, 12, 66380)
            ),
        ),
        migrations.AlterField(
            model_name="targets",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 29, 10, 34, 12, 66380)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
