# Generated by Django 4.1.3 on 2023-04-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecash',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='outcomecash',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='incomecash',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categories', verbose_name='Категория'),
        ),
    ]
