# Generated by Django 4.2.16 on 2024-10-07 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_accumulations_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulations',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 18, 43, 14, 205981)),
        ),
        migrations.AlterField(
            model_name='incomecategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 18, 43, 14, 205981)),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 18, 43, 14, 205981)),
        ),
        migrations.AlterField(
            model_name='outcomecategories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 18, 43, 14, 205981)),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 18, 43, 14, 205981)),
        ),
        migrations.AlterField(
            model_name='targets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 18, 43, 14, 205981)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 18, 43, 14, 205981)),
        ),
    ]
