# Generated by Django 4.2.13 on 2024-06-16 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_accumulations_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("М", "Мужской"), ("Ж", "Женский")],
                default="None",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="accumulations",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 17, 35, 40, 625697)
            ),
        ),
        migrations.AlterField(
            model_name="incomecategories",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 17, 35, 40, 625697)
            ),
        ),
        migrations.AlterField(
            model_name="incomes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 17, 35, 40, 625697)
            ),
        ),
        migrations.AlterField(
            model_name="outcomecategories",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 17, 35, 40, 625697)
            ),
        ),
        migrations.AlterField(
            model_name="outcomes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 17, 35, 40, 625697)
            ),
        ),
        migrations.AlterField(
            model_name="targets",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 17, 35, 40, 625697)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 17, 35, 40, 625697)
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.country"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.city"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.country",
            ),
        ),
    ]
