# Generated by Django 4.1.3 on 2023-04-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_incomecash_category_name_outcomecash_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecash',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='outcomecash',
            name='category_name',
        ),
    ]
