# Generated by Django 4.1.3 on 2023-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_moneybox_box_target_alter_moneybox_box_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='box_target',
            field=models.IntegerField(editable=False, null=True, verbose_name='Конечная цель'),
        ),
    ]
