# Generated by Django 4.1.3 on 2023-05-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_moneybox_box_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneybox',
            old_name='box_target',
            new_name='_box_target',
        ),
    ]
