# Generated by Django 4.2.13 on 2024-06-16 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20240616_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accumulations",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 22, 4, 58, 958783)
            ),
        ),
        migrations.AlterField(
            model_name="incomecategories",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 22, 4, 58, 958783)
            ),
        ),
        migrations.AlterField(
            model_name="incomes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 22, 4, 58, 958783)
            ),
        ),
        migrations.AlterField(
            model_name="outcomecategories",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 22, 4, 58, 958783)
            ),
        ),
        migrations.AlterField(
            model_name="outcomes",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 22, 4, 58, 958783)
            ),
        ),
        migrations.AlterField(
            model_name="targets",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 22, 4, 58, 958783)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 16, 22, 4, 58, 958783)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("М", "Мужской"), ("Ж", "Женский"), ("N", "None")],
                default="None",
                max_length=32,
            ),
        ),
    ]
