# Generated by Django 4.2.16 on 2024-10-10 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Целевая сумма')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления записи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'targets',
            },
        ),
        migrations.RunSQL(
            """INSERT INTO targets(user_id, name, amount, is_deleted, created_at, updated_at)
               SELECT user_id,
                      target_name,
                      target_sum,
                      FALSE,
                      created_at,
                      updated_at
               FROM api_targets"""
        ),
    ]
