# Generated by Django 4.1.3 on 2023-04-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_incomecash_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='deleted_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incomecash',
            name='deleted_category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outcomecash',
            name='deleted_category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
