# Generated by Django 4.1.3 on 2023-04-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_incomecash_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='deleted_name',
        ),
        migrations.RemoveField(
            model_name='incomecash',
            name='deleted_category_name',
        ),
        migrations.RemoveField(
            model_name='outcomecash',
            name='deleted_category_name',
        ),
    ]
