# Generated by Django 4.2.16 on 2024-10-10 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('type', models.CharField(choices=[('income', 'Категория доходов'), ('outcome', 'Категория расходов')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='api.category', verbose_name='Категория')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='api.target', verbose_name='Цель')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operations',
            },
        ),
        migrations.RunSQL(
            """INSERT INTO operations(user_id, type, amount, categories_id, date, created_at, updated_at)
                SELECT t.user_id,
                       'income' as type,
                       t.sum,
                       c.id as category_id,
                       t.created_at::date,
                       t.created_at,
                       t.updated_at
                FROM api_incomes t
                LEFT JOIN api_incomecategories ic_old ON ic_old.id = t.category_id
                LEFT JOIN categories c ON c.user_id = t.user_id
                                          AND c.name = ic_old.name
                                          AND c.is_income;"""
        ),
        migrations.RunSQL(
            """INSERT INTO operations(user_id, type, amount, categories_id, date, created_at, updated_at)
                SELECT t.user_id,
                       'outcome' as type,
                       t.sum,
                       c.id as category_id,
                       t.created_at::date,
                       t.created_at,
                       t.updated_at
                FROM api_outcomes t
                LEFT JOIN api_outcomecategories oc_old ON oc_old.id = t.category_id
                LEFT JOIN categories c ON c.user_id = t.user_id
                                          AND c.name = oc_old.name
                                          AND c.is_outcome;"""
        ),
        migrations.RunSQL(
            """INSERT INTO operations(user_id, type, amount, target_id, date, created_at, updated_at)
                SELECT t_old.user_id,
                       'outcome' as type,
                       o.sum,
                       t.id as target_id,
                       o.created_at::date as date,
                       o.created_at,
                       o.updated_at
                FROM api_accumulations o
                JOIN api_targets t_old ON t_old.id = o.target_id
                JOIN targets t ON t.user_id = t_old.user_id
                                  AND t.name = t_old.target_name;"""
        ),
    ]
