# Generated by Django 4.2.16 on 2024-10-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_fixed',
        ),
    ]
