# Generated by Django 4.1.3 on 2023-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_categories_deleted_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecash',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='outcomecash',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название категории'),
        ),
    ]
