# Generated by Django 4.2.1 on 2024-10-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Код страны')),
                ('name', models.CharField(max_length=56, verbose_name='Краткое название')),
                ('full_name', models.CharField(max_length=56, verbose_name='Полное название')),
            ],
            options={
                'db_table': 'api_countries',
            },
        ),
    ]
