# Generated by Django 4.2.16 on 2024-11-06 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_remove_category_is_fixed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomes",
            name="category",
        ),
        migrations.RemoveField(
            model_name="incomes",
            name="user",
        ),
        migrations.RemoveField(
            model_name="outcomes",
            name="category",
        ),
        migrations.RemoveField(
            model_name="outcomes",
            name="user",
        ),
        migrations.RemoveField(
            model_name="targets",
            name="user",
        ),
        migrations.DeleteModel(
            name="Accumulations",
        ),
        migrations.DeleteModel(
            name="IncomeCategories",
        ),
        migrations.DeleteModel(
            name="Incomes",
        ),
        migrations.DeleteModel(
            name="OutcomeCategories",
        ),
        migrations.DeleteModel(
            name="Outcomes",
        ),
        migrations.DeleteModel(
            name="Targets",
        ),
    ]
