# Generated by Django 4.1.3 on 2023-04-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_incomecash_category_name_outcomecash_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecash',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='outcomecash',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='incomecash',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categories', verbose_name='Категория'),
        ),
    ]
