# Generated by Django 4.1.3 on 2023-05-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_moneybox__box_target_moneybox_box_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybox',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Категория'),
        ),
    ]
