# Generated by Django 4.2.16 on 2024-11-17 08:59
import json
import os

from django.db import migrations, models


def load_data(apps, schema_editor):
    countries = apps.get_model('api', 'Country')

    file_path = os.path.join(os.path.dirname(__file__), 'data/oksm.json')

    with open(file_path, encoding="utf8") as f:
        data = json.load(f)

        country_objects = [
            countries(name=item.get("name"), code=item.get("alfa2"))
            for item in data
        ]
        countries.objects.bulk_create(country_objects, batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_incomes_category_remove_incomes_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=146, verbose_name="Краткое название"),
                ),
                ("code", models.CharField(max_length=3, verbose_name="Альфа-2")),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "db_table": "api_countries",
            },
        ),
        migrations.RunPython(load_data),
    ]
