# Generated by Django 4.2.16 on 2024-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_incomes_category_remove_incomes_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='current_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Текущая сумма'),
        ),
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('achieved', 'Достигнута')], default='in_progress', max_length=15, verbose_name='Статус цели'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('income', 'Категория доходов'), ('outcome', 'Категория расходов'), ('targets', 'Из накоплений')], max_length=10),
        ),
    ]
