# Generated by Django 4.2.16 on 2024-11-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_incomes_category_remove_incomes_user_and_more'),
        ('api', '0015_target_current_sum_target_status_and_more'),
    ]

    operations = [
    ]
