# Generated by Django 4.1.3 on 2023-05-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_moneybox_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('constant', 'Постоянные'), ('once', 'Разовые'), ('accumulate', 'Накопления')], default='constant', max_length=10),
        ),
    ]
