# Generated by Django 4.1.3 on 2023-04-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_incomecash_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categoryName',
            new_name='category_name',
        ),
    ]
