# Generated by Django 4.2.1 on 2024-10-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_countries_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=146, verbose_name='Краткое название'),
        ),
    ]
