# Generated by Django 4.1.3 on 2023-05-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_categories_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneybox',
            name='box_name',
        ),
        migrations.AlterField(
            model_name='moneybox',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Название накопления'),
        ),
    ]
