# Generated by Django 4.2.16 on 2024-11-17 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import api.models.users

def load_data(apps, schema_editor):
    profile = apps.get_model('api', 'Profile')
    user = apps.get_model('api', 'User')

    users = user.objects.all()
    for us in users:
        profile.objects.get_or_create(user=us)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, null=True)),
                ("last_name", models.CharField(max_length=30, null=True)),
                (
                    "gender",
                    models.CharField(
                        null=True,
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to=api.models.users.upload_to),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(load_data),
    ]
