# Generated by Django 4.2.1 on 2024-11-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(default=185, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Пользователь FinanceApp', max_length=30),
        ),
    ]
