# Generated by Django 4.1.3 on 2023-05-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_moneybox_box_name_alter_moneybox_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneybox',
            name='category',
        ),
        migrations.AddField(
            model_name='moneybox',
            name='outcome',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.outcomecash', verbose_name='Название накопления'),
        ),
    ]
