# Generated by Django 4.2.16 on 2024-11-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_target_current_sum_target_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('income', 'Категория доходов'), ('outcome', 'Категория расходов'), ('targets', 'Накопления')], max_length=10),
        ),
    ]
