# Generated by Django 5.1.3 on 2024-12-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_operation_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['type', 'date'], name='operations_type_a738c7_idx'),
        ),
    ]
