# Generated by Django 5.1.3 on 2025-01-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_operation_operations_type_a738c7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
