# Generated by Django 4.1.3 on 2023-05-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_moneybox_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='outcome',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.outcomecash', verbose_name='Название накопления'),
        ),
    ]
