# Generated by Django 5.1.3 on 2025-01-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_currencydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydata',
            name='currency',
            field=models.CharField(max_length=10, unique=True, verbose_name='Связка валют'),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='rate',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Значение курса'),
        ),
    ]
