# Generated by Django 4.1.3 on 2023-05-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_moneybox_category_remove_moneybox_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='box_sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма накопления'),
        ),
        migrations.AlterField(
            model_name='moneybox',
            name='box_target',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Конечная цель'),
        ),
    ]
