# Generated by Django 5.1.3 on 2025-03-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_currencydata_currency_alter_currencydata_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_system',
            field=models.BooleanField(default=True, verbose_name='Признак системной категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_visibility',
            field=models.BooleanField(default=True, verbose_name='Признак видимости категории'),
        ),
    ]
