# Generated by Django 5.1.3 on 2025-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_category_options_category_is_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Признак системной категории'),
        ),
    ]
