# Generated by Django 4.1.3 on 2023-05-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_moneybox_box_sum_alter_moneybox_box_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneybox',
            name='box_name',
        ),
        migrations.AddField(
            model_name='moneybox',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('constant', 'Постоянные'), ('once', 'Разовые'), ('accumulate', 'Накопления')], default='constant', max_length=10),
        ),
    ]
