# Generated by Django 5.1.3 on 2025-04-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_category_is_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
