# Generated by Django 4.1.3 on 2023-05-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_moneybox_box_name_moneybox_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneybox',
            old_name='category',
            new_name='categories',
        ),
    ]
