# Generated by Django 5.1.3 on 2025-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_first_name_profile_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default',
            field=models.IntegerField(choices=[(1, 'default 1'), (2, 'default 2'), (3, 'default 3'), (4, 'default 4'), (5, 'default 5'), (6, 'default 6'), (7, 'default 7'), (8, 'default 8')], null=True),
        ),
    ]
