# Generated by Django 5.1.3 on 2025-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_profile_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default',
            field=models.IntegerField(choices=[(0, 'not default'), (1, 'default 1'), (2, 'default 2'), (3, 'default 3'), (4, 'default 4'), (5, 'default 5'), (6, 'default 6'), (7, 'default 7'), (8, 'default 8')], default=0),
        ),
    ]
