# Generated by Django 5.1.3 on 2025-08-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_profile_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default',
            new_name='defaultAvatar',
        ),
    ]
