# Generated by Django 4.1.3 on 2023-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_categories_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='box_sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма накопления'),
        ),
    ]
