# Generated by Django 4.1.3 on 2023-05-12 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_moneybox_box_name_moneybox_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybox',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания накопления'),
            preserve_default=False,
        ),
    ]
