# Generated by Django 4.1.3 on 2023-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_moneybox_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='date_created',
            field=models.DateField(verbose_name='Дата создания накопления'),
        ),
    ]
