# Generated by Django 4.1.3 on 2023-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_moneybox_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybox',
            name='outcome_cash',
            field=models.ManyToManyField(to='api.outcomecash'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_type',
            field=models.CharField(choices=[('constant', 'Постоянные'), ('once', 'Разовые'), ('accumulate', 'Накопления')], default='constant', max_length=10),
        ),
    ]
