# Generated by Django 4.1.3 on 2023-05-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_moneybox_outcome_cash_alter_categories_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneybox',
            name='outcome_cash',
        ),
    ]
