# Generated by Django 4.1.3 on 2023-05-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_moneybox_outcome_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='box_sum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outcomecash', verbose_name='Сумма накопления'),
        ),
    ]
