# Generated by Django 4.1.3 on 2023-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_moneybox_box_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneybox',
            name='box_sum',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма накопления'),
        ),
    ]
