# Generated by Django 4.1.3 on 2023-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_moneybox_box_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybox',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
