# Generated by Django 4.1.3 on 2023-05-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_moneybox_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneybox',
            name='is_hidden',
        ),
    ]
