# Generated by Django 4.1.3 on 2023-05-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_date_created_moneybox_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecash',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.categories', verbose_name='Категория'),
        ),
    ]
