# Generated by Django 4.1.3 on 2023-05-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_box_target_moneybox_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecash',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='moneybox',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='outcomecash',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Категория'),
        ),
    ]
