# Generated by Django 4.1.3 on 2023-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_incomecash_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='income_outcome',
            field=models.CharField(choices=[('income', 'Категория доходов'), ('outcome', 'Категория расходов'), ('money_box', 'Категория накоплений')], default='income', max_length=11),
        ),
    ]
