apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment-dev
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend-dev
  template:
    metadata:
      annotations:
        fluentd.active: 'true'
      labels:
        app: django-backend-dev
    spec:
      containers:
        - name: django
          image: freenance/backend-dev:{{IMAGE_TAG}}
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "300m"
          envFrom:
            - secretRef:
                name: finance-dev-secret
          volumeMounts:
            - name: django-storage
              mountPath: /app/static
          lifecycle:
            postStart:
              exec:
                command: ["python", "manage.py", "migrate"]
      volumes:
        - name: django-storage
          persistentVolumeClaim:
            claimName: django-pvc-dev
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: django-app-service-dev
spec:
  selector:
    app: django-backend-dev
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30040
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{NAMESPACE}}
  name: django-pvc-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage-dev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-pvc-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage-dev
  hostPath:
    path: /data/{{NAMESPACE}}
