apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{NAMESPACE}}
  name: postgresdb-pv-{{NAMESPACE}}
  labels:
    type: local
    app: postgresdb-prod
spec:
  storageClassName: local
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/{{NAMESPACE}}/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{NAMESPACE}}
  name: postgresdb-pvc-{{NAMESPACE}}
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: postgresdb
  labels:
    app: postgresdb-prod
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30050
  selector:
    app: postgresdb-prod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb-prod
  serviceName: postgresdb-headless
  template:
    metadata:
      labels:
        app: postgresdb-prod
      annotations:
        fluentd.active: 'true'
    spec:
      containers:
        - name: postgresdb
          image: postgres:16
          env:
            - name: TZ
              value: "UTC-3"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret-prod
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret-prod
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret-prod
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgresdb-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "145Mi"
              cpu: "25m"
            limits:
              memory: "180Mi"
              cpu: "160m"
      volumes:
        - name: postgresdb-data
          persistentVolumeClaim:
            claimName: postgresdb-pvc-{{NAMESPACE}}
